### ISSUE TITLE
Doesnt work on vs Code for windows 

### ISSUE THREAD

**Issue by ganeshShetty98** [kufii/CodeSnap#37]
Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by NatoCMI** [comment]
Hm, I just tried it and it works on my environment

```yaml
Version: 1.48.0-insider
Commit: 2277c8e2a3e1cc630a6397301ba54a1dccd8a60d
Date: 2020-08-07T11:32:09.993Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```
