### ISSUE TITLE
Command 'CodeSnap 📸' resulted in an error (panel.postMessage is not a function)

### ISSUE THREAD

**Issue by NatoBoram** [kufii/CodeSnap#46]
```yaml
Version: 1.49.0-insider
Commit: b6d4fec3714ff897f72c1dab8cc02b7421a8f131
Date: 2020-09-01T05:54:42.740Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```
